# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
 
jobs:
  print-inputs:
   runs-on: ubuntu-latest
   steps:
    - name: Show the input values
      run: |
        echo ${{variables.FOLDERNAME}}
       
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        if [ -f ./day1/requirements.txt ]; then pip install -r ./day1/requirements.txt; fi
    
    - name: Run the pythoncode
      run: |
        python ./day1/currentdateime.py
