name: Invoke External Work Flow
permissions:
 contents: write
on: 
 workflow_dispatch:

jobs:
  call-reusable:
   uses: ./.github/workflows/reusablewf.yml
   with: 
     cardo: 45843858438
     cardtype: visa
     

